//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotoElectronico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voto_Votante
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int Edad { get; set; }
        public byte AntecedentesByte { get; set; }

        public bool Antecedentes
        {
            get { return AntecedentesByte != 0; }  // Si el valor es distinto de 0, es true
            set { AntecedentesByte = value ? (byte)1 : (byte)0; }  // Convierte true a 1, false a 0
        }
    }
}
